# Generated by Django 5.2.17 on 2026-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="region",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
